<?php
/**
 * Easylife_Translation extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE_EASY_TRANSLATION.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category       Easylife
 * @package        Easylife_Translation
 * @copyright      Copyright (c) 2013
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Js for operations
 *
 * @category    Easylife
 * @package     Easylife_Translation
 * @author      Marius Strajeru <marius.strajeru@gmail.com>
 */
?>
<?php $operations = Mage::getSingleton('translation/operation')->getOperationAsOptions()?>
<script type="text/javascript">
//<![CDATA[
var EasylifeTranslationOperation = new Class.create();
EasylifeTranslationOperation.prototype = {
    initialize : function(config){
        this.config = config;
        this.field = $('operation_operation');
        this.field.onchange = this.changeOperation.bindAsEventListener(this);
        this.modules = $('operation_modules');
        this.modules.onchange = this.changeModules.bindAsEventListener(this);
        this.changeOperation();
        this.changeModules();
    },
    changeOperation : function(){
        var fields = this.getAllFields();
        if ($(this.field).value == ''){
            allowedFields = [];
        }
        else{
            var allowedFields = this.config[$(this.field).value].fields;
        }
        for (i in fields){
            if (fields.hasOwnProperty(i)){
                if (typeof allowedFields[fields[i]] != 'undefined' && allowedFields[fields[i]] != 0){
                    $('operation_' + fields[i]).up(1).show();
                    $('operation_' + fields[i]).disabled = false;
                }
                else{
                    $('operation_' + fields[i]).up(1).hide();
                    $('operation_' + fields[i]).disabled = true;
                }
            }
        }
    },
    getAllFields: function(){
        return ['locale', 'ignore', 'themes', 'modules', 'use_any'];
    },
    changeModules: function(){
        if ($(this.modules).value == 1){
            $('module-grid').hide();
        }
        else{
            $('module-grid').show();
        }
    }
}
var operations = new EasylifeTranslationOperation(<?php echo Mage::helper('core')->jsonEncode($operations)?>);
//]]>
</script>